name: vendify
description: "Un robusto sistema de Punto de Venta (POS) móvil que te permite gestionar ventas, productos y reportes de forma local, sin necesidad de internet, ¡todo desde la palma de tu mano!"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.2
  go_router: ^16.2.0
  sqflite: ^2.0.0
  path: ^1.0.0
  shared_preferences: ^2.0.0
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
